#!/bin/bash
VERSION=$1
if [[ "$VERSION" == "" ]];then
  echo "Usage: $0 <version>"
  exit
fi

GROUPID="com.github.xuges"
NAME="natives"
JAR="$NAME-$VERSION.jar"
META="META-INF/maven/$GROUPID/$NAME"
OUTPUT=`pwd`/output

cd src/main/java

DATE=`date`
mkdir -p $META
cat > $META/pom.properties << EOF
#Generated by Maven
#$DATE
groupId=$GROUPID
artifactId=$NAME
version=$VERSION
EOF

cat > $META/pom.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>$GROUPID</groupId>
    <artifactId>$NAME</artifactId>
    <version>$VERSION</version>
</project>
EOF

jar -cf $JAR $META/* `find . -name "*.class"`
rm -rf META-INF

# for cls in `find . -name "*.class"`;do
#   jar -uf $JAR $cls
# done

mkdir -p $OUTPUT
mv $JAR $OUTPUT/